#config.yaml

run_name: "fashion_cnn_v1_lr_001" # Mudar a cada experimento

data:
  root: "./data"
  batch_size: 128
  num_workers: 2

model:
  in_channels: 1
  h1_channels: 32
  h2_channels: 64
  linear_dim: 128
  dropout_rate: 0.3
  num_classes: 10

training:
  device: "cuda" # 'cuda' ou 'cpu'
  seed: 42
  optimizer: "Adam"
  learning_rate: 0.001
  num_epochs: 10

outputs:
  log_dir: "outputs/logs"
  checkpoint_dir: "outputs/checkpoints"